#!/usr/bin/env python3
"""Cross-run union + variance across all 3 required Phase 2 runs, per the
brief's explicit design: "run the full scan at least 3 times on different
days; report the union plus per-run variance."

"Union" here means a real per-host OR over `h3_supported` across the 3
runs (a host counts as HTTP/3-capable if ANY run found it so) -- NOT the
naive multi-file concatenation that analysis/load.py's default guards
against elsewhere in this pipeline (see load.py's CANONICAL_PROBE_RUN_ID
comment for why that's a different, wrong thing). This is the proper
aggregation the brief actually asked for, computed once here rather than
ad hoc.

Ownership class for the union set uses the classification observed in
whichever run(s) found the host HTTP/3-capable; where those runs
disagree on ownership class for the same host (possible if, e.g., a
transient DNS answer pointed at a different ASN on one run), the host is
flagged "unstable" and counted separately rather than silently
resolved one way.

Writes output/tables/cross_run_*.{csv,tex} and prints a run-by-run
comparison for both RQ1 (sector adoption) and RQ2 (ownership class).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from analysis.load import load_probe_runs  # noqa: E402
from analysis.rq1_adoption import SECTOR_ORDER, SECTOR_LABELS  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "output" / "tables"

RUN_IDS = ["run-2026-08-05b", "run-2026-08-07", "run-2026-08-08"]


def _write(df: pd.DataFrame, name: str, caption: str):
    df.to_csv(OUTPUT_DIR / f"{name}.csv", index=False)
    cols = list(df.columns)
    lines = [
        f"% Generated by analysis/cross_run_variance.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering", f"\\caption{{{caption}}}", f"\\label{{tab:{name.replace('_','-')}}}",
        r"\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", r"\hline",
        " & ".join(cols) + r" \\", r"\hline",
    ]
    for _, row in df.iterrows():
        lines.append(" & ".join(str(v) for v in row) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    (OUTPUT_DIR / f"{name}.tex").write_text("\n".join(lines))
    print(f"--- {caption} ---")
    print(df.to_string(index=False))
    print()


def build_union(run_dfs: dict[str, pd.DataFrame]) -> pd.DataFrame:
    """One row per (host, apex/www), h3_supported = OR across all 3 runs.
    sector/domain/host_type are stable across runs (same corpus every
    time) so taken from whichever run has the host."""
    merged = None
    for run_id, df in run_dfs.items():
        sub = df[["host", "domain", "host_type", "sector", "h3_supported", "ownership_class"]].copy()
        sub = sub.rename(columns={
            "h3_supported": f"h3_{run_id}",
            "ownership_class": f"owner_{run_id}",
        })
        merged = sub if merged is None else merged.merge(
            sub[["host", f"h3_{run_id}", f"owner_{run_id}"]], on="host", how="outer"
        )

    h3_cols = [c for c in merged.columns if c.startswith("h3_")]
    owner_cols = [c for c in merged.columns if c.startswith("owner_")]
    merged["h3_supported_union"] = merged[h3_cols].fillna(False).any(axis=1)

    def _resolve_owner(row):
        owners = {row[c] for c, h3c in zip(owner_cols, h3_cols) if row.get(h3c) is True}
        owners.discard(None)
        if not owners:
            return "not_h3_capable"
        if len(owners) == 1:
            return next(iter(owners))
        return "unstable_across_runs"

    merged["ownership_class_union"] = merged.apply(_resolve_owner, axis=1)
    return merged


def rq1_per_run_and_union(run_dfs: dict[str, pd.DataFrame], union_df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for sector in SECTOR_ORDER:
        row = {"Sector": SECTOR_LABELS[sector]}
        for run_id, df in run_dfs.items():
            apex = df[(df["host_type"] == "apex") & (df["sector"] == sector)]
            if len(apex):
                row[run_id] = round(100 * apex["h3_supported"].sum() / len(apex), 1)
            else:
                row[run_id] = None
        apex_union = union_df[(union_df["host_type"] == "apex") & (union_df["sector"] == sector)]
        row["union"] = round(100 * apex_union["h3_supported_union"].sum() / len(apex_union), 1) if len(apex_union) else None
        row["n"] = len(apex_union)
        rows.append(row)
    total_row = {"Sector": "All confirmed sectors"}
    for run_id, df in run_dfs.items():
        apex = df[(df["host_type"] == "apex") & (df["sector"].isin(SECTOR_ORDER))]
        total_row[run_id] = round(100 * apex["h3_supported"].sum() / len(apex), 1)
    apex_union_all = union_df[(union_df["host_type"] == "apex") & (union_df["sector"].isin(SECTOR_ORDER))]
    total_row["union"] = round(100 * apex_union_all["h3_supported_union"].sum() / len(apex_union_all), 1)
    total_row["n"] = len(apex_union_all)
    rows.append(total_row)
    return pd.DataFrame(rows)


def rq2_per_run_and_union(run_dfs: dict[str, pd.DataFrame], union_df: pd.DataFrame) -> pd.DataFrame:
    classes = ["foreign_cdn", "foreign_hosting", "nepali_hosting", "mixed", "unknown"]
    labels = {"foreign_cdn": "Foreign CDN", "foreign_hosting": "Foreign hosting (non-CDN)",
              "nepali_hosting": "Nepali hosting", "mixed": "Mixed (A/AAAA disagree)", "unknown": "Unknown"}
    rows = []
    for cls in classes:
        row = {"Ownership class": labels[cls]}
        for run_id, df in run_dfs.items():
            apex = df[(df["host_type"] == "apex") & df["h3_supported"]]
            n = len(apex)
            row[run_id] = f"{(apex['ownership_class'] == cls).sum()} ({100 * (apex['ownership_class'] == cls).sum() / n:.1f}%)" if n else "0 (0.0%)"
        apex_union = union_df[(union_df["host_type"] == "apex") & union_df["h3_supported_union"]]
        n_union = len(apex_union)
        count_union = (apex_union["ownership_class_union"] == cls).sum()
        row["union"] = f"{count_union} ({100 * count_union / n_union:.1f}%)" if n_union else "0 (0.0%)"
        rows.append(row)
    unstable = (union_df[(union_df["host_type"] == "apex") & union_df["h3_supported_union"]]["ownership_class_union"] == "unstable_across_runs").sum()
    if unstable:
        rows.append({"Ownership class": "Unstable across runs", "run-2026-08-05b": "-", "run-2026-08-07": "-", "run-2026-08-08": "-", "union": str(unstable)})
    return pd.DataFrame(rows)


def compute_union_rq1_table(union_df: pd.DataFrame) -> pd.DataFrame:
    """Same shape as rq1_adoption.compute() (Sector, h3_capable, total,
    adoption_rate_pct) but built from the 3-run union rather than a
    single run -- lets figures.py and the manuscript reuse the existing
    single-run plotting function unchanged, just fed different numbers."""
    from analysis.rq1_adoption import SECTOR_LABELS

    rows = []
    for sector in SECTOR_ORDER:
        apex = union_df[(union_df["host_type"] == "apex") & (union_df["sector"] == sector)]
        h3_capable = int(apex["h3_supported_union"].sum())
        total = len(apex)
        rows.append({
            "Sector": SECTOR_LABELS[sector], "h3_capable": h3_capable, "total": total,
            "adoption_rate_pct": round(100 * h3_capable / total, 1) if total else 0.0,
        })
    return pd.DataFrame(rows)


def compute_union_ownership_table(union_df: pd.DataFrame) -> pd.DataFrame:
    """Same shape as rq2_ownership.compute_ownership() (Ownership class,
    count, share_pct), built from the 3-run union."""
    labels = {"foreign_cdn": "Foreign CDN", "foreign_hosting": "Foreign hosting (non-CDN)",
              "nepali_hosting": "Nepali hosting", "mixed": "Mixed (A/AAAA disagree)", "unknown": "Unknown"}
    apex_union = union_df[(union_df["host_type"] == "apex") & union_df["h3_supported_union"]]
    counts = apex_union["ownership_class_union"].value_counts()
    total = len(apex_union)
    rows = []
    for cls in ["foreign_cdn", "foreign_hosting", "nepali_hosting", "mixed", "unknown"]:
        c = int(counts.get(cls, 0))
        if c == 0 and cls not in ("foreign_cdn", "foreign_hosting", "nepali_hosting"):
            continue
        rows.append({"Ownership class": labels[cls], "count": c, "share_pct": round(100 * c / total, 1) if total else 0.0})
    return pd.DataFrame(rows)


def main():
    run_dfs = {rid: load_probe_runs(run_ids=[rid]) for rid in RUN_IDS}
    for rid, df in run_dfs.items():
        if df.empty:
            print(f"Missing run: {rid} -- run probe/scan.py --run-id {rid} first.")
            return

    union_df = build_union(run_dfs)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    rq1 = rq1_per_run_and_union(run_dfs, union_df)
    _write(rq1, "cross_run_rq1_adoption", "RQ1: HTTP/3 adoption rate by sector, per run and 3-run union (%)")

    rq2 = rq2_per_run_and_union(run_dfs, union_df)
    _write(rq2, "cross_run_rq2_ownership", "RQ2: ownership class among HTTP/3-capable apex hosts, per run and 3-run union")

    n_hosts = len(union_df)
    n_capable_any = union_df["h3_supported_union"].sum()
    n_capable_all3 = union_df[[f"h3_{r}" for r in RUN_IDS]].fillna(False).all(axis=1).sum()
    print(f"Union: {n_capable_any}/{n_hosts} hosts HTTP/3-capable in >=1 of 3 runs")
    print(f"Stable: {n_capable_all3}/{n_hosts} hosts HTTP/3-capable in ALL 3 runs")
    print(f"Flaky: {n_capable_any - n_capable_all3} hosts capable in some but not all runs")
    print(f"Wrote tables to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
