#!/usr/bin/env python3
"""RQ1 -- adoption by sector. Reads data/raw/, writes
output/tables/rq1_adoption.{csv,tex}.

Apex hosts only (not apex+www) so each row is one domain, not two --
adoption-by-sector is a claim about domains, not about the apex/www split
(that split is its own finding, see rq2's apex/www divergence note).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from analysis.load import load_probe_runs  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "output" / "tables"

SECTOR_ORDER = ["government", "banking", "telecom", "media", "education", "ecommerce_fintech"]
SECTOR_LABELS = {
    "government": "Government", "banking": "Banking", "telecom": "Telecom",
    "media": "Media", "education": "Education", "ecommerce_fintech": "E-commerce/Fintech",
}


def compute(df: pd.DataFrame) -> pd.DataFrame:
    apex = df[df["host_type"] == "apex"]
    grouped = apex.groupby("sector").agg(
        h3_capable=("h3_supported", "sum"),
        total=("h3_supported", "count"),
    )
    grouped["adoption_rate_pct"] = (100 * grouped["h3_capable"] / grouped["total"]).round(1)
    grouped = grouped.reindex(SECTOR_ORDER).dropna(how="all")
    grouped.index = [SECTOR_LABELS.get(s, s) for s in grouped.index]
    grouped["h3_capable"] = grouped["h3_capable"].astype(int)
    grouped["total"] = grouped["total"].astype(int)
    grouped.index.name = "Sector"
    return grouped.reset_index()


def to_latex(table: pd.DataFrame) -> str:
    lines = [
        r"% RQ1: HTTP/3 adoption by sector. Generated by analysis/rq1_adoption.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{HTTP/3 adoption by sector (apex hosts, run-2026-08-05b)}",
        r"\label{tab:rq1-adoption}",
        r"\begin{tabular}{lrrr}",
        r"\hline",
        r"Sector & HTTP/3-capable & Total & Rate (\%) \\",
        r"\hline",
    ]
    for _, row in table.iterrows():
        lines.append(f"{row['Sector']} & {row['h3_capable']} & {row['total']} & {row['adoption_rate_pct']} \\\\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines)


def main():
    df = load_probe_runs()
    if df.empty:
        print("No probe data found in data/raw/. Run probe/scan.py first.")
        return
    table = compute(df)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = OUTPUT_DIR / "rq1_adoption.csv"
    tex_path = OUTPUT_DIR / "rq1_adoption.tex"
    table.to_csv(csv_path, index=False)
    tex_path.write_text(to_latex(table))

    print(table.to_string(index=False))
    print(f"\nWrote {csv_path}, {tex_path}")


if __name__ == "__main__":
    main()
