#!/usr/bin/env python3
"""RQ2 -- ownership (foreign CDN vs. origin-native), the paper's central
question. Writes output/tables/rq2_ownership.{csv,tex} and
rq2_cdn_concentration.{csv,tex}.
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from analysis.load import load_probe_runs  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "output" / "tables"

CLASS_LABELS = {
    "foreign_cdn": "Foreign CDN", "foreign_hosting": "Foreign hosting (non-CDN)",
    "nepali_hosting": "Nepali hosting", "unknown": "Unknown", "mixed": "Mixed (A/AAAA disagree)",
}
CLASS_ORDER = ["foreign_cdn", "foreign_hosting", "nepali_hosting", "mixed", "unknown"]


def compute_ownership(df: pd.DataFrame) -> pd.DataFrame:
    apex_h3 = df[(df["host_type"] == "apex") & (df["h3_supported"])]
    counts = apex_h3["ownership_class"].value_counts()
    counts = counts.reindex(CLASS_ORDER).dropna().astype(int)
    total = counts.sum()
    table = pd.DataFrame({
        "Ownership class": [CLASS_LABELS.get(c, c) for c in counts.index],
        "count": counts.values,
        "share_pct": (100 * counts.values / total).round(1),
    })
    return table


def compute_cdn_concentration(df: pd.DataFrame) -> pd.DataFrame:
    """Per-operator breakdown of the foreign_cdn class. Re-derives each
    individual ASN's class the same way load.py re-derives the host-level
    ownership_class (against the current config, not the value stored at
    probe time), so this stays consistent with compute_ownership() above
    even after config/asn_classification.yaml is edited."""
    from probe.asn_probe import classify_asn

    apex_h3 = df[(df["host_type"] == "apex") & (df["h3_supported"]) & (df["ownership_class"] == "foreign_cdn")]
    names = Counter()
    for asns in apex_h3["asns"]:
        cdn_asns = [a for a in asns if classify_asn(a.get("asn"), a.get("as_name")) == "foreign_cdn"]
        if cdn_asns:
            names[cdn_asns[0]["as_name"].split(" - ")[0]] += 1
    total = sum(names.values())
    table = pd.DataFrame({
        "CDN operator": list(names.keys()),
        "count": list(names.values()),
    }).sort_values("count", ascending=False)
    table["share_of_foreign_cdn_pct"] = (100 * table["count"] / total).round(1) if total else 0
    return table.reset_index(drop=True)


def to_latex(table: pd.DataFrame, caption: str, label: str) -> str:
    cols = list(table.columns)
    header = " & ".join(cols) + r" \\"
    lines = [
        f"% Generated by analysis/rq2_ownership.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering", f"\\caption{{{caption}}}", f"\\label{{{label}}}",
        r"\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", r"\hline", header, r"\hline",
    ]
    for _, row in table.iterrows():
        lines.append(" & ".join(str(v) for v in row) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines)


def main():
    df = load_probe_runs()
    if df.empty:
        print("No probe data found in data/raw/. Run probe/scan.py first.")
        return

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    ownership = compute_ownership(df)
    ownership.to_csv(OUTPUT_DIR / "rq2_ownership.csv", index=False)
    (OUTPUT_DIR / "rq2_ownership.tex").write_text(
        to_latex(ownership, "HTTP/3 ownership class among HTTP/3-capable apex hosts", "tab:rq2-ownership"))
    print("=== RQ2: ownership ===")
    print(ownership.to_string(index=False))

    concentration = compute_cdn_concentration(df)
    concentration.to_csv(OUTPUT_DIR / "rq2_cdn_concentration.csv", index=False)
    (OUTPUT_DIR / "rq2_cdn_concentration.tex").write_text(
        to_latex(concentration, "CDN operator concentration among foreign\\_cdn hosts", "tab:rq2-cdn-concentration"))
    print("\n=== RQ2: CDN concentration (Correctness requirement 4) ===")
    print(concentration.to_string(index=False))

    print(f"\nWrote tables to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
