#!/usr/bin/env python3
"""RQ3 -- configuration quality among HTTP/3-capable hosts. Writes several
small tables to output/tables/, since RQ3 bundles several distinct
sub-questions (versions, groups, issuers, 0-RTT, HTTPS-RR, advertised-vs-
actual) rather than one.

Uses apex+www (not apex-only like RQ1/RQ2) -- RQ3 is about configuration of
whichever hosts actually support HTTP/3, and apex/www of the same domain
can be configured differently (see the apex/www divergence note this
script also computes).
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from analysis.load import load_probe_runs  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "output" / "tables"

VERSION_LABELS = {"0x00000001": "v1 (RFC 9000)", "0x6b3343cf": "v2 (RFC 9369)"}


def write_table(df: pd.DataFrame, name: str, caption: str):
    df.to_csv(OUTPUT_DIR / f"{name}.csv", index=False)
    cols = list(df.columns)
    lines = [
        f"% Generated by analysis/rq3_config.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering", f"\\caption{{{caption}}}", f"\\label{{tab:{name.replace('_','-')}}}",
        r"\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", r"\hline",
        " & ".join(cols) + r" \\", r"\hline",
    ]
    for _, row in df.iterrows():
        lines.append(" & ".join(str(v) for v in row) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    (OUTPUT_DIR / f"{name}.tex").write_text("\n".join(lines))
    print(f"--- {caption} ---")
    print(df.to_string(index=False))
    print()


def main():
    df = load_probe_runs()
    if df.empty:
        print("No probe data found in data/raw/. Run probe/scan.py first.")
        return
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    h3 = df[df["h3_supported"]]

    versions = h3["quic_negotiated_version"].value_counts()
    versions = pd.DataFrame({
        "QUIC version": [VERSION_LABELS.get(v, v) for v in versions.index],
        "count": versions.values,
        "share_pct": (100 * versions.values / versions.sum()).round(1),
    })
    write_table(versions, "rq3_quic_versions", "QUIC version negotiated (HTTP/3-capable hosts)")

    groups = h3["tls_key_exchange_group"].value_counts()
    groups = pd.DataFrame({
        "Key-exchange group": groups.index, "count": groups.values,
        "share_pct": (100 * groups.values / groups.sum()).round(1),
    })
    write_table(groups, "rq3_tls_groups",
                "TLS 1.3 key-exchange group (classical only -- hybrid PQ groups not observable by this probe, see phases.md)")

    issuers = h3["tls_cert_issuer"].value_counts().head(10)
    issuers = pd.DataFrame({"Certificate issuer": issuers.index, "count": issuers.values})
    write_table(issuers, "rq3_cert_issuers", "Certificate issuers among HTTP/3-capable hosts (top 10)")

    zrtt_attempted = h3[h3["zero_rtt_attempted"] == True]
    zrtt_row = pd.DataFrame([{
        "attempted": len(zrtt_attempted),
        "accepted": int((zrtt_attempted["zero_rtt_accepted"] == True).sum()),
        "accepted_pct": round(100 * (zrtt_attempted["zero_rtt_accepted"] == True).sum() / max(len(zrtt_attempted), 1), 1),
    }])
    write_table(zrtt_row, "rq3_zero_rtt", "0-RTT acceptance among HTTP/3-capable hosts")

    total = len(df)
    https_rr = pd.DataFrame([{
        "https_rr_present": int(df["https_rr_present"].sum()),
        "https_rr_present_pct": round(100 * df["https_rr_present"].sum() / total, 1),
        "https_rr_alpn_h3": int(df["https_rr_alpn_h3"].sum()),
        "total_hosts": total,
    }])
    write_table(https_rr, "rq3_https_rr", "HTTPS/SVCB (RR type 65) presence, all hosts")

    mismatch = df[df["h3_advertised"] != df["h3_supported"]]
    adv_not_sup = mismatch[mismatch["h3_advertised"] & ~mismatch["h3_supported"]]
    sup_not_adv = mismatch[mismatch["h3_supported"] & ~mismatch["h3_advertised"]]
    mismatch_row = pd.DataFrame([{
        "total_hosts": total,
        "mismatch_count": len(mismatch),
        "mismatch_pct": round(100 * len(mismatch) / total, 1),
        "advertised_not_supported": len(adv_not_sup),
        "supported_not_advertised": len(sup_not_adv),
    }])
    write_table(mismatch_row, "rq3_advertised_vs_actual", "Advertised (Alt-Svc/HTTPS-RR) vs. actual QUIC support mismatch")

    print(f"Wrote tables to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
