#!/usr/bin/env python3
"""RQ4 -- H2 vs. H3 performance, same-origin only. Writes
output/tables/rq4_*.{csv,tex} from perf/handshake_bench.py (Phase 4a,
handshake-only) and perf/pageload_bench.py (Phase 4b, full page load,
netlog-verified) output.

Phase 4b tables use ONLY netlog-verified trials (`verified == True`) for
any timing comparison -- an unverified trial's forced protocol didn't
actually take effect on the wire (see perf/netlog_verify.py), so
including it would silently blend an H2 result into what's reported as
H3's number, or vice versa. The verified-vs-discarded rate itself is
reported as its own table, since a low rate is a finding about path
reliability, not just a data-quality footnote.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
from scipy.stats import mannwhitneyu

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from analysis.load import load_handshake_bench_runs, load_pageload_bench_runs  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "output" / "tables"


def write_table(df: pd.DataFrame, name: str, caption: str):
    df.to_csv(OUTPUT_DIR / f"{name}.csv", index=False)
    cols = list(df.columns)
    lines = [
        f"% Generated by analysis/rq4_performance.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering", f"\\caption{{{caption}}}", f"\\label{{tab:{name.replace('_','-')}}}",
        r"\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", r"\hline",
        " & ".join(cols) + r" \\", r"\hline",
    ]
    for _, row in df.iterrows():
        lines.append(" & ".join(str(v) for v in row) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    (OUTPUT_DIR / f"{name}.tex").write_text("\n".join(lines))
    print(f"--- {caption} ---")
    print(df.to_string(index=False))
    print()


def main():
    df = load_handshake_bench_runs()
    if df.empty:
        print("No handshake benchmark data found in data/raw/. Run perf/handshake_bench.py first.")
        return
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # --- Overview: trial counts and success rate per protocol ---
    overview = df.groupby("protocol").agg(
        trials=("success", "size"),
        successes=("success", "sum"),
    ).reset_index()
    overview["success_rate_pct"] = (overview["successes"] / overview["trials"] * 100).round(1)
    overview["Protocol"] = overview["protocol"].map({"h3": "HTTP/3 (QUIC)", "h2": "HTTP/2 (TCP+TLS)"})
    overview = overview[["Protocol", "trials", "successes", "success_rate_pct"]].rename(
        columns={"trials": "Trials", "successes": "Successes", "success_rate_pct": "Success rate (%)"})
    write_table(overview, "rq4_overview", "RQ4: handshake benchmark trial counts and success rate, by protocol")

    # --- Failure reasons (successful trials excluded) ---
    fail = df[df["success"] == False]
    if not fail.empty:
        fail_tbl = fail.groupby(["protocol", "failure_reason"]).size().reset_index(name="count")
        fail_tbl = fail_tbl.rename(columns={"protocol": "Protocol", "failure_reason": "Failure reason", "count": "Count"})
        write_table(fail_tbl, "rq4_failures", "RQ4: handshake failure reasons, by protocol")

    # --- Handshake duration: median/IQR per protocol, successful trials only ---
    ok = df[(df["success"] == True) & df["handshake_duration_ms"].notna()]
    summary_rows = []
    for proto, label in (("h3", "HTTP/3 (QUIC)"), ("h2", "HTTP/2 (TCP+TLS)")):
        vals = ok[ok["protocol"] == proto]["handshake_duration_ms"]
        summary_rows.append({
            "Protocol": label, "n": len(vals),
            "Median (ms)": round(vals.median(), 1),
            "IQR low (ms)": round(vals.quantile(0.25), 1),
            "IQR high (ms)": round(vals.quantile(0.75), 1),
            "Mean (ms)": round(vals.mean(), 1),
            "Std (ms)": round(vals.std(), 1),
        })
    duration_summary = pd.DataFrame(summary_rows)
    write_table(duration_summary, "rq4_handshake_duration",
                "RQ4: handshake completion time (first packet to complete), by protocol, "
                "successful trials only")

    # --- Mann-Whitney U test: H3 vs H2 handshake duration ---
    h3_vals = ok[ok["protocol"] == "h3"]["handshake_duration_ms"]
    h2_vals = ok[ok["protocol"] == "h2"]["handshake_duration_ms"]
    stat, pvalue = mannwhitneyu(h3_vals, h2_vals, alternative="two-sided")
    faster = "HTTP/3" if h3_vals.median() < h2_vals.median() else "HTTP/2"
    mw_tbl = pd.DataFrame([{
        "n (H3)": len(h3_vals), "n (H2)": len(h2_vals),
        "U statistic": round(stat, 1), "p-value": f"{pvalue:.3e}",
        "Median faster": faster,
        "Significant at alpha=0.05": "Yes" if pvalue < 0.05 else "No",
    }])
    write_table(mw_tbl, "rq4_mannwhitney",
                "RQ4: Mann-Whitney U test, H3 vs. H2 handshake duration (two-sided)")

    # --- Per-domain median handshake time, both protocols, plus delta ---
    per_domain = ok.groupby(["domain", "protocol"])["handshake_duration_ms"].median().unstack("protocol")
    per_domain = per_domain.rename(columns={"h3": "H3 median (ms)", "h2": "H2 median (ms)"})
    per_domain["H3 - H2 (ms)"] = (per_domain["H3 median (ms)"] - per_domain["H2 median (ms)"]).round(1)
    per_domain = per_domain.round(1).reset_index()
    write_table(per_domain, "rq4_per_domain",
                f"RQ4: per-domain median handshake time, H3 vs. H2 (n={len(per_domain)} domains)")

    n_h3_faster = (per_domain["H3 - H2 (ms)"] < 0).sum()
    n_h2_faster = (per_domain["H3 - H2 (ms)"] > 0).sum()
    print(f"Domains where H3 is faster (lower median): {n_h3_faster}/{len(per_domain)}")
    print(f"Domains where H2 is faster (lower median): {n_h2_faster}/{len(per_domain)}")

    # ==================================================================
    # Phase 4b -- full page-load timing (netlog-verified trials only)
    # ==================================================================
    pl = load_pageload_bench_runs()
    if pl.empty:
        print("No page-load benchmark data found -- skipping Phase 4b tables.")
        print(f"Wrote tables to {OUTPUT_DIR}")
        return

    # --- Verification rate: itself a finding, not just a footnote ---
    verif = pl.groupby("protocol").agg(
        trials=("verified", "size"),
        verified=("verified", "sum"),
    ).reset_index()
    verif["verified_rate_pct"] = (verif["verified"] / verif["trials"] * 100).round(1)
    discard_by_protocol = (
        pl[~pl["verified"]].groupby(["protocol", "discard_reason"]).size()
        .reset_index(name="count")
    )
    verif["Protocol"] = verif["protocol"].map({"h3": "HTTP/3 (QUIC)", "h2": "HTTP/2 (TCP+TLS)"})
    verif_tbl = verif[["Protocol", "trials", "verified", "verified_rate_pct"]].rename(
        columns={"trials": "Trials", "verified": "Netlog-verified", "verified_rate_pct": "Verified rate (%)"})
    write_table(verif_tbl, "rq4_pageload_verification",
                "RQ4 (Phase 4b): netlog-verification rate, by protocol -- unverified trials excluded from timing tables below")
    if not discard_by_protocol.empty:
        discard_tbl = discard_by_protocol.rename(
            columns={"protocol": "Protocol", "discard_reason": "Discard reason", "count": "Count"})
        write_table(discard_tbl, "rq4_pageload_discards",
                    "RQ4 (Phase 4b): reasons unverified page-load trials were excluded")

    # --- Page-load duration: median/IQR per protocol, verified trials only ---
    ok_pl = pl[pl["verified"] & pl["load_event_ms"].notna()]
    metrics = [
        ("dom_content_loaded_ms", "DOMContentLoaded (ms)"),
        ("load_event_ms", "Load event (ms)"),
        ("first_contentful_paint_ms", "First contentful paint (ms)"),
    ]
    for col, label in metrics:
        rows = []
        for proto, plabel in (("h3", "HTTP/3 (QUIC)"), ("h2", "HTTP/2 (TCP+TLS)")):
            vals = ok_pl[ok_pl["protocol"] == proto][col].dropna()
            if vals.empty:
                continue
            rows.append({
                "Protocol": plabel, "n": len(vals),
                "Median (ms)": round(vals.median(), 1),
                "IQR low (ms)": round(vals.quantile(0.25), 1),
                "IQR high (ms)": round(vals.quantile(0.75), 1),
                "Mean (ms)": round(vals.mean(), 1),
            })
        if rows:
            write_table(pd.DataFrame(rows), f"rq4_pageload_{col}",
                        f"RQ4 (Phase 4b): {label}, by protocol, netlog-verified trials only")

    # --- Mann-Whitney U: H3 vs H2 load-event time (the closest analogue to Phase 4a's headline number) ---
    h3_load = ok_pl[ok_pl["protocol"] == "h3"]["load_event_ms"].dropna()
    h2_load = ok_pl[ok_pl["protocol"] == "h2"]["load_event_ms"].dropna()
    if len(h3_load) > 0 and len(h2_load) > 0:
        stat, pvalue = mannwhitneyu(h3_load, h2_load, alternative="two-sided")
        faster = "HTTP/3" if h3_load.median() < h2_load.median() else "HTTP/2"
        mw_pl = pd.DataFrame([{
            "n (H3)": len(h3_load), "n (H2)": len(h2_load),
            "U statistic": round(stat, 1), "p-value": f"{pvalue:.3e}",
            "Median faster": faster,
            "Significant at alpha=0.05": "Yes" if pvalue < 0.05 else "No",
        }])
        write_table(mw_pl, "rq4_pageload_mannwhitney",
                    "RQ4 (Phase 4b): Mann-Whitney U test, H3 vs. H2 page load-event time (two-sided, netlog-verified trials only)")

    # --- Failure reasons among unsuccessful page loads ---
    pl_fail = pl[pl["success"] == False]
    if not pl_fail.empty:
        fail_tbl = pl_fail.groupby(["protocol", "failure_reason"]).size().reset_index(name="count")
        fail_tbl = fail_tbl.rename(columns={"protocol": "Protocol", "failure_reason": "Failure reason", "count": "Count"})
        write_table(fail_tbl, "rq4_pageload_failures", "RQ4 (Phase 4b): page-load failure reasons, by protocol")

    # --- Per-domain median load time, both protocols ---
    per_domain_pl = ok_pl.groupby(["domain", "protocol"])["load_event_ms"].median().unstack("protocol")
    per_domain_pl = per_domain_pl.rename(columns={"h3": "H3 median (ms)", "h2": "H2 median (ms)"})
    if "H3 median (ms)" in per_domain_pl.columns and "H2 median (ms)" in per_domain_pl.columns:
        per_domain_pl["H3 - H2 (ms)"] = (per_domain_pl["H3 median (ms)"] - per_domain_pl["H2 median (ms)"]).round(1)
        per_domain_pl = per_domain_pl.round(1).reset_index()
        write_table(per_domain_pl, "rq4_pageload_per_domain",
                    f"RQ4 (Phase 4b): per-domain median page load-event time, H3 vs. H2 (n={len(per_domain_pl)} domains)")
        n_h3_faster_pl = (per_domain_pl["H3 - H2 (ms)"] < 0).sum()
        n_h2_faster_pl = (per_domain_pl["H3 - H2 (ms)"] > 0).sum()
        print(f"Page loads: domains where H3 is faster (lower median): {n_h3_faster_pl}/{len(per_domain_pl)}")
        print(f"Page loads: domains where H2 is faster (lower median): {n_h2_faster_pl}/{len(per_domain_pl)}")

    print(f"Wrote tables to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
