#!/usr/bin/env python3
"""RQ5 -- UDP path viability. Writes output/tables/rq5_*.{csv,tex} from
viability/udp_path_test.py output.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
from analysis.load import load_viability_runs  # noqa: E402

OUTPUT_DIR = REPO_ROOT / "output" / "tables"


def write_table(df: pd.DataFrame, name: str, caption: str):
    df.to_csv(OUTPUT_DIR / f"{name}.csv", index=False)
    cols = list(df.columns)
    lines = [
        f"% Generated by analysis/rq5_viability.py -- do not edit by hand.",
        r"\begin{table}[t]", r"\centering", f"\\caption{{{caption}}}", f"\\label{{tab:{name.replace('_','-')}}}",
        r"\begin{tabular}{l" + "r" * (len(cols) - 1) + "}", r"\hline",
        " & ".join(cols) + r" \\", r"\hline",
    ]
    for _, row in df.iterrows():
        lines.append(" & ".join(str(v) for v in row) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    (OUTPUT_DIR / f"{name}.tex").write_text("\n".join(lines))
    print(f"--- {caption} ---")
    print(df.to_string(index=False))
    print()


def main():
    vdf = load_viability_runs()
    if vdf.empty:
        print("No viability data found in data/raw/. Run viability/udp_path_test.py first.")
        return
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    handshake = vdf.drop_duplicates("host")[["host", "operator", "handshake_success", "handshake_ms", "mtu_all_ok", "mtu_fail_sizes"]]
    handshake = handshake.rename(columns={
        "handshake_success": "Handshake OK", "handshake_ms": "Handshake (ms)",
        "mtu_all_ok": "MTU clean 1200-1500B", "mtu_fail_sizes": "MTU failures at (bytes)",
    })
    write_table(handshake, "rq5_handshake_mtu", "RQ5: handshake completion and MTU/PMTUD sweep, reference servers")

    idle = vdf.pivot_table(index=["host", "operator"], columns="idle_s", values="resumed_ok", aggfunc="first")
    idle.columns = [f"survives_{c}s" for c in idle.columns]
    idle = idle.reset_index()
    write_table(idle, "rq5_idle_survival",
                "RQ5: idle-period connection survival by interval (see phases.md -- reflects server idle-timeout policy, not confirmed NAT rebinding)")

    throughput = vdf.drop_duplicates("host")[["host", "operator", "throughput_quic_bps", "throughput_tcp_h2_bps"]].copy()
    throughput["quic_vs_tcp_ratio"] = (throughput["throughput_quic_bps"] / throughput["throughput_tcp_h2_bps"]).round(2)
    write_table(throughput, "rq5_throughput", "RQ5: QUIC vs. TCP/H2 throughput, reference servers' own homepages")

    print(f"Wrote tables to {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
